version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sixchan
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 54321:5432
